# Generated by Django 3.2.3 on 2021-05-19 09:16

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdvisorName', models.CharField(max_length=122, null=True)),
                ('AdvisorImage', models.ImageField(default='default.jpg', upload_to=home.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField(blank=True, null=True)),
                ('BookingTime', models.DateTimeField(blank=True, null=True, verbose_name='%y-%m-%d %H:%M:%S')),
                ('AdvisorId', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='home.advisor')),
            ],
        ),
    ]
